---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse
- name: lighthouse
  src: git@github.com:dm-chv/lighthouse-role.git
  scm: git
  name: lighthouse
- name: vector
  src: git@github.com:dm-chv/vector-role.git
  scm: git
  name: vector