---
- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector
- name: Install Clickhouse
  hosts: clickhouse
  roles:
  - clickhouse
  
- name: Install Lighthouse
  hosts: lighthouse

  pre_tasks:
    - name: Lighthouse | Install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  roles:
  - lighthouse